version: '2'
services:
  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - ../data/db:/data/db
  permit-service:
    image: permit-service:local
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    environment:
      PMTS_PORT: 8080
      HOST_NAME: permit-service
      PMTS_MONGO_HOST: mongodb://mongo:27017/permit
      PMTS_GRANT_TYPE: client_credentials
      PMTS_AUDIENCE: "_LCF5avgIpoXSWhY5Jl8mMi0Q~4_~R"
      PMTS_APPROVAL_URL: http://approval-system-server/api/v1/request
      PMTS_SPIKE_SERVICE: spike-service:8080
      PMTS_ELASTIC_APM_IGNORE_URLS: '/grpc.health.v1.Health/Check'
      ELASTICSEARCH_URL: http://52.169.253.183:9200
      LOG_INDEX: kdrive
      LOG_LEVEL: debug
      HEALTH_CHECK_INTERVAL: 5
      ELASTIC_APM_SERVER_URL: 'http://52.169.253.183:8200'
      ELASTIC_APM_SERVICE_NAME: 'permit-service'
      ELASTIC_APM_SERVICE_VERSION: '0.1'
      ELASTIC_APM_ENVIRONMENT: 'development'
      ELASTIC_APM_ACTIVE: 'true'
      ELASTIC_APM_CAPTURE_BODY: 'all'
      ELASTIC_APM_METRICS_INTERVAL: '10s'
    ports:
      - 8080:8080
    depends_on:
      - mongo
      - spike-service
  spike-service:
    image:  drivehub.azurecr.io/meateam/spike-service:appID
    environment:
      AUDIENCE: "AUDIENCE"
      SPIKE_CLIENT_ID: "EPBpjCiczupCXZgBEq3ARZCinUt4LSXtOsVrI1Ub"
      SPIKE_CLIENT_SECRET: "u5qxEK0sy17ReZ7t8aVeN1gCcdI9hRiM78i9J_9Z6jA2YWcvbgczcchKqZ4WnXOsdT6jxmuVCLC3~RXuVcE5EsOG4JJi~B8AJQSB"
      REDIS_URL: 'redis://redis:6379'
      SPIKE_TOKEN_URL: "https://spike.westeurope.cloudapp.azure.com:1337/oauth2/token"
      SPIKE_PUBLIC_KEY_FULL_PATH: "/usr/src/app/utils/publickey.pem"
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    depends_on:
      - redis
    ports:
      - '8081:8080'
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  approval-system-server:
    image: registry.gitlab.com/yesodot/rnd/terminal-rabaz/dropbox/microservices/approval-system-server
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      NODE_ENV: production
      AUTH_CALLBACK_URL: /auth/callback
      PORT: 80
      DB_SERVERS: mongo
      DB_NAME: approvals
      SHRAGA_URL: http://13.79.7.3
      SPIKE_REDIS_HOST: redis://redis
      SPIKE_URL: https://spike.westeurope.cloudapp.azure.com:1337/oauth2/token
      CLIENT_URL: http://approval-system-client/myApprovals
      DRIVE_URL: http://test-sh.northeurope.cloudapp.azure.com
      STATUS_SERVICE_URL: http://status-api:80/api/status
      PUSH_SERVICE_URL: http://push-service
      SPIKE_PUSH_SERVICE_AUDIENCE: JOPQO6k7n~bOGrnbwJFikLOW9f2AEO
      APM_ACTIVE: 0
    ports:
      - 80:80
    depends_on:
      - redis
      - mongo
  status-api:
    image: registry.gitlab.com/yesodot/rnd/terminal-rabaz/dropbox/microservices/status-api
    ports:
      - 8006:80
    environment: 
      MONGO_URL: mongodb://mongo:27017/



